config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/works_config', as: 'rails_admin'
  devise_for :works
  # mount RailsAdmin::Engine => '/works_config', as: 'rails_admin'
  # devise_for :works

  resources :amounts, only: [:show]do
    resources :links, only: [:show, :index]
  end
get 'links/:id/go' => 'links#go'
get 'contact', to: 'contact#send_mail'
post 'contact', to: 'contact#send_mail'


  resources :referers, only: [:index]
  root 'products#index'
  get 'category/new', to: 'categories#new'
  post 'category/new', to: 'categories#create'
  get 'category/edit/:id', to: 'categories#edit'
  put 'category/edit/:id', to: 'categories#update'
  patch 'category/edit/:id', to: 'categories#update'
  get 'brand/new', to: 'brands#new'
  post 'brand/new', to: 'brands#create'
  get 'brand/edit/:id', to: 'brands#edit'
  put 'brand/edit/:id', to: 'brands#update'
  patch 'brand/edit/:id', to: 'brands#update'
  get 'product/new', to: 'products#new'
  post 'product/new', to: 'products#create'


 resources :products, only: [:edit, :update]

  #resources :products, only: [:new, :create, :edit, :update]
  resources :categories, path: '',only: [:show] do
    resources :brands, path: '', only: [:show] do
      resources :products, path: '',only: [:show] do
        resources :customers, only: [:create]

      end
    end
  end


resources :referers, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :products
  has_many :categories, through: :products

  validates :name, uniqueness: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
 before_action :authenticate_work!, only: [:new,:create]
  def show
    @brand = Brand.friendly.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(params_brand)
    if @brand.save
      redirect_to :back
    else
      render :new
    end
  end


  def edit
    @brand = Brand.friendly.find(params[:id])
  end

  def update
    @brand = Brand.friendly.find(params[:id])
   if @brand.update(params_brand)
      redirect_to root_path
   else
    render :edit
    end
  end

  private

  def params_brand
    params.require(:brand).permit!
 end

 def referers
  if request.referer.nil? || !request.referer.include?("/assets")
    Referer.create(url: request.referer, ip_address: request.remote_ip, user_agent: request.user_agent, path: request.path_info)
  end
 end
end

app/views/brands/edit.html.erb
<div class="container">
 <div class="well">
  <%= form_for @brand, url: "#{@brand.id}" do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
    <br><br>
  <div class="form-group">
    <%= f.label :keyword, class: "control-label" %>
    <%= f.text_field :keyword, class: "form-control" %>
  </div>
    <br><br>
  <div class="form-group">
    <%= f.label :meta_description, class: "control-label" %>
    <%= f.text_area :meta_description, rows: 2 , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "control-label" %>
    <%= f.text_area :description, rows: 10 , class: "form-control"%>
  </div>
    <%= f.submit "Toevoegen", class: "btn btn-primary" %>
  <% end %>
  <br><br><br>
  <% brand = Brand.all %>
  <% brand.each do |brand| %>
    <ul>
      <li><%= brand.name  %></li>
    </ul>
  <% end %>
 </div>
</div>

app/views/brands/new.html.erb
<div class="container">
 <div class="well">
  <%= form_for @brand, url: brand_new_path do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
    <br><br>
  <div class="form-group">
    <%= f.label :keyword, class: "control-label" %>
    <%= f.text_field :keyword, class: "form-control" %>
  </div>
    <br><br>
  <div class="form-group">
    <%= f.label :meta_description, class: "control-label" %>
    <%= f.text_area :meta_description, rows: 2 , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "control-label" %>
    <%= f.text_area :description, rows: 10 , class: "form-control"%>
  </div>
    <%= f.submit "Toevoegen", class: "btn btn-primary" %>
  <% end %>
  <br><br><br>
  <% brand = Brand.all %>
  <% brand.each do |brand| %>
    <ul>
      <li><%=brand.name  %></li>
    </ul>
  <% end %>
 </div>
</div>

app/views/brands/show.html.erb
<!-- meta info -->
<% cat_new =[] %>
<%  @brand.categories.each do |cat| %>
 <% if request.path.include?(cat.slug)%>
 <% cat_new << cat %>
   <% end %>
  <% end %>
  <% first_cat = cat_new[0]%>

<% title "#{@brand.name} #{first_cat.name} Vergelijken"%>
<% meta_tag :description, "#{@brand.name} #{first_cat.name} Vergelijken, #{@brand.meta_description}."%>

<header class="main-header">
    <div class="container">
        <h1 class="page-title"><%= "#{@brand.name} #{first_cat.name} Vergelijken" %></h1>
          <ol class="breadcrumb pull-right">
            <li><a href="/">Home</a></li>
            <!-- Categorie Naam -->
          <% cat_new =[] %>
          <%  @brand.categories.each do |cat| %>
             <% if request.path.include?(cat.slug)%>
             <% cat_new << cat %>
            <% end %>
          <% end %>
            <% first_cat = cat_new[0]%>
            <li><%= link_to first_cat.name, category_path(first_cat) %></li>
            <!-- einde categorie naam -->
            <li class="active"><a href="#"><%= @brand.name %></a></li>
            <% if work_signed_in? %>
            <a href="/brand/edit/<%= @brand.slug%>">Edit</a>
            <% end %>
        </ol>
    </div>
</header>



<!-- brand Products -->
<div class="col-md-10 col-md-offset-1">
            <div class="row" >
              <% @brand.products.each do |product| %>
              <% if request.path.include?(product.category.slug)%>
                <div class="col-lg-4 col-md-6 mix category-smartphone" data-price="64900" data-date="20130521" data-popularity="3">
                    <div class="ec-box">
                        <div class="ec-box-header">
                          <%= link_to product.title, category_brand_product_path(product.category, product.brand, product)  %>
                          <h5><%= link_to product.category.name, category_path(product.category) %> </h5>
                        </div>
                        <% if product.images.any? %>
                        <% image = product.images[0] %>
                        <a href="#"><img src="<%= image.picture.url(:square) %>"></a>
                        <% end %>
                        <div class="ec-box-footer">
                          <% if product.amounts_today.any?%>
                             <span class="label label-primary">&euro; <%= product.min_amount_today.price.round%></span>
                            <% else %>
                             <span class="label label-primary">Geen Prijs Gevonden.</span>
                           <% end %>
                            <br><br>
                            <% if product.amounts_today.any?%>
                              <%= link_to "Goedkoopste winkel" , amount_link_path(product.min_amount_today.id, product.min_amount_today.links.last), rel: "nofollow", class: "button button-block button-rounded button-highlight button-large"%><!-- product.min_amount_today.url-->
                             <% else %>
                              <p class="button button-block button-rounded button-highlight button-large">Geen Prijs Gevonden.</p>
                              <% end %>
                          
                            <br>
                            <%= link_to "Prijs Vergelijken", category_brand_product_path(product.category, product.brand, product), class: "button button-block button-rounded button-primary button-large" %>



                        </div>
                    </div>
                </div>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div> <!-- container -->
<ul class="nav nav-pills nav-justified ar-nav-pills  center-block margin-bottom">
    <li><a href="#1" data-toggle="tab"><i class="fa fa-check-square-o"></i><%= @brand.name %></a></li>
    <li class="active"><a href="#2" data-toggle="tab"><i class="fa fa-check-square-o"></i>Aanbiedingen </a></li>
    <li><a href="#3" data-toggle="tab"><i class="fa fa-check-square-o"></i> Meer informatie</a></li>
</ul>

<div class="tab-content margin-top">
    <div class="tab-pane" id="1">
      <% if @brand.description.present? %>
       <%= @brand.description %>
       <% end %>
    </div>
    <div class="tab-pane active" id="2">
       <div class="container">
   	      <div class="row">
             <div class="span12">
             		<div class="thumbnail center well well-small text-center">
                   <h2>Ontvang Aanbiedingen in je email!</h2>
                    <p>Schrijf je in voor onze Nieuwsbrief.</p>
                    <form action="" method="post">
                       <div class="input-prepend"><span class="add-on"><i class="icon-envelope"></i></span>
                           <input type="text" id="" name="" placeholder="Naam" class="form-control" >
                           <br><br>
                           <input type="text" id="" name="" placeholder="email adres" class="form-control" >
                       </div>
                       <br />
                       <input type="submit" class="btn btn-info" value="Verstuur!" />
                    </form>
                 </div>
             </div>
         	</div>
       </div>
    </div>
    <div class="tab-pane" id="3">
        ...
    </div>
</div>
<!-- brand Products end  -->
<% content_for :analytics do %>
 <%= render "layouts/analytics" %>
<% end %>