config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/works_config', as: 'rails_admin'
  devise_for :works
  # mount RailsAdmin::Engine => '/works_config', as: 'rails_admin'
  # devise_for :works

  resources :amounts, only: [:show]do
    resources :links, only: [:show, :index]
  end
get 'links/:id/go' => 'links#go'
get 'contact', to: 'contact#send_mail'
post 'contact', to: 'contact#send_mail'


  resources :referers, only: [:index]
  root 'products#index'
  get 'category/new', to: 'categories#new'
  post 'category/new', to: 'categories#create'
  get 'category/edit/:id', to: 'categories#edit'
  put 'category/edit/:id', to: 'categories#update'
  patch 'category/edit/:id', to: 'categories#update'
  get 'brand/new', to: 'brands#new'
  post 'brand/new', to: 'brands#create'
  get 'brand/edit/:id', to: 'brands#edit'
  put 'brand/edit/:id', to: 'brands#update'
  patch 'brand/edit/:id', to: 'brands#update'
  get 'product/new', to: 'products#new'
  post 'product/new', to: 'products#create'


 resources :products, only: [:edit, :update]

  #resources :products, only: [:new, :create, :edit, :update]
  resources :categories, path: '',only: [:show] do
    resources :brands, path: '', only: [:show] do
      resources :products, path: '',only: [:show] do
        resources :customers, only: [:create]

      end
    end
  end


resources :referers, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :title, presence: true

  validates :ean, uniqueness: true

  belongs_to :category
  belongs_to :brand
  has_many :images, dependent: :destroy
  has_many :amounts, dependent: :destroy
  has_many :bullets, dependent: :destroy
  has_many :customers  #Email met prijs waarschuwing
  has_many :specifications, dependent: :destroy
# product types categories
  has_many :beamers
  has_many :televisons
  has_many :refrigerators
  has_many :washing_machines
  has_many :boor_machines
  has_many :espresso_machines
  has_many :auto_radios

  accepts_nested_attributes_for :bullets
  accepts_nested_attributes_for :specifications
  accepts_nested_attributes_for :beamers
  accepts_nested_attributes_for :televisons
  accepts_nested_attributes_for :refrigerators
  accepts_nested_attributes_for :washing_machines
  accepts_nested_attributes_for :boor_machines
  accepts_nested_attributes_for :espresso_machines
  accepts_nested_attributes_for :auto_radios



  def amounts_today # prijzen van vandaag!
      self.amounts.where("created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def unique_shops # unique shops 1 bol, coolblue, wehkamp per product.
    if self.amounts_today.any?
      self.amounts_today.order(:shop).to_a.uniq do |x|
      x.shop
      x.url
      x.price
    end
  else
    self.amounts.order(:price).to_a.uniq do |x|
      x.shop
      x.url
      x.price
    end
  end
  end

  def min_amount_today #min Prijs van vandaag
    if self.amounts_today.any?
       self.amounts_today.order(:price).first
    else
       self.amounts.order(:price).first
    end
  end
 def min_amount
   if self.amounts_today.any?
    if  self.amounts.order(:price).first.price < self.amounts_today.order(:price).first.price
      self.amounts.order(:price).first
    else
      nil
    end
  end
 end

 def price_difference
   if self.amounts_today.any?
     if self.amounts.where("created_at >= ?", Time.zone.now.yesterday).order(:price).first.price == self.amounts.where("created_at >= ?", Time.zone.now.beginning_of_day).order(:price).first.price
       false
     elsif self.amounts.where("created_at >= ?", Time.zone.now.yesterday).order(:price).first.price < self.amounts.where("created_at >= ?", Time.zone.now.beginning_of_day).order(:price).first.price
       nr1 = self.amounts.where("created_at >= ?", Time.zone.now.yesterday).order(:price).first.price / 100
       n2 = nr1 * self.amounts.where("created_at >= ?", Time.zone.now.beginning_of_day).order(:price).first.price
       return n2 - self.amounts.where("created_at >= ?", Time.zone.now.yesterday).order(:price).first.price
     else
       false
     end
   end
 end

def self.search(search)
  where("ean LIKE ?", "%#{search}%")
end



# amounts.where("created_at >= ?", Time.zone.now.beginning_of_day)
end



# prices = []
# if self.amounts.where("created_at >= ?", Time.zone.now.beginning_of_day).any?
# self.amounts.where("created_at >= ?", Time.zone.now.beginning_of_day).each do |amount|
#   prices << amount
# end
# else
#   self.amounts.each do |amount|
#     prices << amount
#   end
# end
# return prices.min

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_work!, only: [:new,:create, :edit, :update]
  def index
    @products = Product.order(created_at: :desc).limit(9)
    @categories = Category.all
    if params[:search]
    @products = Product.search(params[:search]).order("created_at DESC")
  else
    @products = Product.order(created_at: :desc).limit(9)
  end
    referers
  end

  def show
    @product = Product.friendly.find(params[:id])
    referers
  end

  def new
    @product = Product.new

  end

  def create
    @product = Product.new(params_product)
    if @product.save
      if params[:pictures]
        #===== The magic is here ;)
        params[:pictures].each { |image|
          @product.images.create(picture: image)
        }
      end
      @product.short_description = "#{@product.title} Kopen? <br>
                                  Bij Vergelijk.tips Kunt uw de prijzen vergelijken.
                                   wij controleren de prijzen van vele webshops."
      @product.meta_description = "vergelijk de prijzen van de #{@product.title} bij verschillende webshops.
                                  De juiste prijs vind je op VERGELIJK.TIPS ✅ veel webshops ✅ laagste prijzen ✅ bespaar geld."
      @product.save
      # @product.amounts.create(price: 0.0, url: "/", shop: "Onbekend").links.create(link: "/")
      redirect_to edit_product_path(@product)
    else
      render :new
    end
  end
 def edit
   @product = Product.friendly.find(params[:id])
   @product.specifications.build

   specs


   bullets
 end

def update
   @product = Product.friendly.find(params[:id])

   if @product.update(params_product)
     if params[:pictures]
       params[:pictures].each { |image|
         @product.images.create(picture: image)
       }
     end
     redirect_to category_brand_product_path(@product.category, @product.brand, @product)
   end
end


private


  def bullets
    if @product.bullets.count < 4
      @product.bullets.build
    end
  end

  def referers
   if request.referer.nil? || !request.referer.include?("/assets")
     Referer.create(url: request.referer, ip_address: request.remote_ip, user_agent: request.user_agent, path: request.path_info)
   end
  end

  # def delete_images
  #   params[:pictures_ids].each do |img|
  #         @product.images.find_by(image_id: img).destroy
  #   end
  # end

  def specs
    case
    when @product.category.name.downcase == "beamers" && @product.beamers.count < 1
         @product.beamers.build
    when  @product.category.name.downcase == "tv" && @product.televisons.count < 1
          @product.televisons.build
    when  @product.category.name.downcase == "koelkasten" &&  @product.refrigerators.count < 1
          @product.refrigerators.build
    when @product.category.name.downcase == "wasmachines" &&  @product.washing_machines.count < 1
         @product.washing_machines.build
   when  @product.category.name.downcase == "boormachines" && @product.boor_machines.count < 1
         @product.boor_machines.build
   when  @product.category.name.downcase == "espressomachine" && @product.espresso_machines.count < 1
         @product.espresso_machines.build
   when  @product.category.name.downcase == "autospeakers" && @product.auto_radios.count < 1
         @product.auto_radios.build
      else

      end
 end

 def params_product
     params.require(:product).permit(:product_model, :short_description, :keyword, :meta_description, :title, :description, :ean, :category_id, :brand_id, pictures_ids: [],
                                        bullets_attributes: [
                                                             :id,
                                                             :title,
                                                             :description
                                                             ],
                                 specifications_attributes: [
                                                             :id,
                                                             :content,
                                                             :label,
                                                             :type
                                                             ],
                                     beamers_attributes: [
                                                          :id,
                                                          :resolutie,
                                                          :lumen,
                                                          :aansluitingen,
                                                          :geluidsniveau,
                                                          :drie_d,
                                                          :speaker,
                                                          :gewicht,
                                                          :diepte,
                                                          :hoogte,
                                                          :breedte
                                                          ],
                                     televisons_attributes: [
                                                             :id,
                                                             :beeldscherm_grote,
                                                             :resolutie,
                                                             :schermtype,
                                                             :energie_klasse,
                                                             :surround_systeem,
                                                             :processor,
                                                             :aantal_speakers,
                                                             :connections,
                                                             :ci,
                                                             :drie_d,
                                                             :smart_tv,
                                                             :curved,
                                                             :soort_decoder,
                                                             :hoogte,
                                                             :breedte,
                                                             :diepte,
                                                             :gewicht,
                                                             :wifi,
                                                             :hdmi,
                                                             :usb
                                                           ],
                                     refrigerators_attributes: [
                                                                :id,
                                                                :koelkast_model,
                                                                :energie_klasse,
                                                                :soort,
                                                                :inhoud_koelruimte,
                                                                :inhoud_vriesruimte,
                                                                :geluidsniveau,
                                                                :breedte,
                                                                :hoogte,
                                                                :diepte,
                                                                :gewicht,
                                                                :no_frost,
                                                                :low_frost,
                                                                :automatisch_ontdooien,
                                                                :snel_invriezen,
                                                                :ijdispenser,
                                                                :open_deur_alarm,
                                                                :superkoelen,
                                                                :draaideur_richting_aanpasbaar,
                                                                :temperatuur_instelbaar
                                                               ],
                                   washing_machines_attributes: [:id,
                                                                :energie_klasse,
                                                                :geluidsniveau,
                                                                :breedte,
                                                                :hoogte,
                                                                :diepte,
                                                                :gewicht,
                                                                :belading,
                                                                :bouw,
                                                                :wasdroger,
                                                                :maximum_vulgewicht,
                                                                :toeren_per_minuut,
                                                                :display,
                                                                :resttijd_indicatie,
                                                                :starttijd_keuze,
                                                                :waterlekage_beveiliging,
                                                                :intergreerbaar
                                                                ],
                                      boor_machines_attributes:[

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_stuff.html.erb
<% if @product.amounts.any? %>
<% @product.amounts_today.each do |amount| %>

 <img src="<%= amount.links.last.link %>" class="invisible"/>
 <%end%>
 <%end%>

app/views/products/index.html.erb
<div class="col-md-10 col-md-offset-1">
            <h2 class="section-title ">Nieuwste Producten</h2>

            <div class="row" >
              <!-- filter begin -->

              <!-- filter end -->

              <% @products.each do |product| %>
                <div class="col-lg-4 col-md-6 mix category-smartphone" data-price="64900" data-date="20130521" data-popularity="3">
                    <div class="ec-box">
                        <div class="ec-box-header"><a href="#"><%= link_to product.title, category_brand_product_path(product.category, product.brand, product) %></a>
                          <h5><%= link_to product.category.name, category_path(product.category) %> | <%= link_to product.brand.name, category_brand_path(product.category, product.brand) %> </h5>
                        </div>
                        <% if product.images.any? %>
                        <% image = product.images[0] %>
                        <a href="#"><img src="<%= image.picture.url(:square) %>"></a>
                        <% end %>
                        <div class="ec-box-footer">
                          <% if product.amounts_today.any?%>
                             <span class="label label-primary">&euro; <%= product.min_amount_today.price.round%></span>
                            <% else %>
                             <span class="label label-primary">Geen Prijs Gevonden.</span>
                           <% end %>
                            <br>
                            <br>
                           <% if product.amounts_today.any?%>
                             <%= link_to "Goedkoopste winkel" , amount_link_path(product.min_amount_today.id, product.min_amount_today.links.last), rel: "nofollow", class: "button button-block button-rounded button-highlight button-large"%><!-- product.min_amount_today.url-->
                            <% else %>
                             <p class="button button-block button-rounded button-highlight button-large">Geen Prijs Gevonden.</p>
                             <% end %>
                            <br>
                            <%= link_to "Prijs Vergelijken", category_brand_product_path(product.category, product.brand, product), class: "button button-block button-rounded button-primary button-large" %>

                        </div>
                    </div>
                </div>
                <% end %>
                  <div class="col-md-12">
                      <h2 class="section-title ">Categoriën</h2>
                  </div>
             <div class="row">
                <% @categories.each do |category| %>
              <div class="col-md-3 col-sm-6">
                <div class="content-box box-default animated fadeInUp animation-delay-10>
                  <span class="icon-ar icon-ar-lg icon-ar-round icon-ar-inverse">
                    <i class="fa fa-check-square"></i>
                  </span>
                  <h4 class="content-box-title"><%= link_to category.name, category_path(category) %></h4>
                </div>
              </div>
                <% end %>
                </div>
            </div>
        </div>
    </div>
</div> <!-- container -->
<% content_for :analytics do %>
 <%= render "layouts/analytics" %>
<% end %>

app/views/products/new.html.erb
<div class="container">
  <div class="well">
          <%= form_for @product, url: product_new_path,   :html => { multipart: true } do |f| %>
          <div class="form-group">
            <%= f.label :title, class: "control-label" %>
            <%= f.text_field :title, class: "form-control col-md-10"  %>
          </div>
          <div class="form-group">
            <%= f.label :ean, class: "control-label" %>
            <%= f.text_field :ean, class: "form-control"  %>
          </div>
          <br><br>
          <div class="form-group">
            <%= f.label :product_model, class: "control-label" %>
            <%= f.text_field :product_model, class: "form-control col-md-10"  %>
          </div>
          <div class="form-group">
            <%= f.label :short_description, class: "control-label" %>
            <%= f.text_area :short_description, rows: 3, class: "form-control col-md-10"  %>
          </div>
          <br><br>


          <br><br>
          <div class="form-group">
            <%= f.label :keyword, class: "control-label" %>
            <%= f.text_field :keyword, class: "form-control col-md-10"  %>
          </div>
          <br><br>
          <div class="form-group">
            <%= f.label :meta_description, class: "control-label" %>
            <%= f.text_area :meta_description, rows: 2, class: "form-control col-md-10", placeholder: "Niet Nodig" %>
          </div>
          <br><br>
         <div>
           <%= f.label :description, class: "control-label" %>
          <%= f.text_area :description, id: "edit", class: "form-control col-md-10", rows: "10", placeholder: "Niet Nodig" %>
        </div>


           <br>
           <br>
          <div class="form-group">
            <%= f.label :images, class: "" %>
            <%= file_field_tag "pictures[]", type: :file, multiple: true, class: "" %>
          </div>

          <div class="form-group">
             <%= collection_select(:product, :category_id, Category.all, :id, :name, {}, {:class =>"form-control"}) do |cb| %>
             <%= cb.label(class: 'check_box') {cb.check_box(class: 'checkbox') + cb.text} %>
           <% end %>
         </div>
         <div class="form-group">
           <div class="">
          <%= collection_select(:product, :brand_id, Brand.all, :id, :name, {}, {:class =>"form-control"}) do |cb| %>
          <%= cb.label(class: 'ggg') {cb.check_box(class: 'ddd') + cb.text} %>
          <% end %>
          </div>
        </div>

           <%= f.submit "submit", class: "btn btn-primary"%>
           <% end %>
 </div>
</div>

app/views/products/show.html.erb
<% title "#{@product.title} Prijs?" %>
<% meta_tag :description, @product.meta_description %>

<header class="main-header">
    <div class="container">
        <a href="/"><h1 class="page-title">Home</h1></a>
          <ol class="breadcrumb pull-right">
            <% if work_signed_in? %>
            <li><%= link_to "Edit", edit_product_path(@product) %></li>
            <% end %>
            <li><%= link_to @product.category.name, category_path(@product.category) %></li>
            <li><%= link_to @product.brand.name, category_brand_path(@product.category, @product.brand) %></li>
            <li class="active"><a href="#"><%= @product.title %></a></li>
        </ol>
    </div>
</header>
<div class="container">
    <h2 class="section-title no-margin-top"><%=@product.title %></h2>
    <div class="row">
        <div class="col-md-4">

            <ul class="bxslider">
              <%  @product.images.each do |image| %>
                <% if @product.amounts.empty? %>
                  <li><a href="#" rel="nofollow"><%= image_tag image.picture.url(:medium) %></a></li>
                  <% else %>
                    <li><a href="<%= amount_link_path(@product.min_amount_today.id, @product.min_amount_today.links.last) %>" rel="nofollow"><%= image_tag image.picture.url(:medium) %></a></li>
                  <% end %>
              <% end %>
            </ul>

            <!-- <div id="bx-pager"> -->

              <%  @product.images.each do |image| %>
                <% if @product.amounts.empty? %>
                  <a data-slide-index="0" href="#" rel="nofollow"><img src="<%= image.picture.url(:thumb) %>"></a>
                  <% else %>
                    <a data-slide-index="0" href="<%= amount_link_path(@product.min_amount_today.id, @product.min_amount_today.links.last) %>" rel="nofollow"><img src="<%= image.picture.url(:thumb) %>"></a>
                  <% end %>
              <% end %>
            <!-- </div> -->
        </div>

        <div class="col-md-5">
          <% if @product.amounts_today.any? %>
            <h3 class="no-margin-top"><%= @product.brand.name %> <%= @product.product_model %> prijs: &euro;<%= @product.min_amount_today.price %></h3>
            <% elsif @product.amounts.empty?  %>
              <h3 class="no-margin-top"><%= @product.brand.name %> <%= @product.product_model %> prijs: Geen Prijs gevonden</h3>
              <% else %>
              <h3 class="no-margin-top"><%= @product.brand.name %> <%= @product.product_model %> prijs: Geen Prijs gevonden</h3>
            <% end %>
            <hr>
            <% if @product.amounts_today.any? %>
            <div class="content-box box-default">

             <h5> E-mail mij wanneer de prijs lager is dan:&euro;<%= @product.min_amount_today.price %> </h5>
             <% if @product.min_amount != nil %>
              <em>De prijs was &euro;<%= @product.min_amount.price %> op <%= @product.min_amount.created_at.strftime("%d-%m-%Y") %>. </em>
              <% else %>
               <em>De prijs was nog nooit zo laag!</em>
              <% end %>

          <%= render "customers/form" %>

              </div>
              <% end %>
              <br><br><br>
              <% if @product.amounts_today.any? %>
              <%= link_to "Laagste Prijs", amount_link_path(@product.min_amount_today.id, @product.min_amount_today.links.last), rel: "nofollow", class: "button button-block button-rounded button-highlight button-large" %>
              <% else %>
                <a href="#" class="button button-block button-rounded button-highlight button-large">Geen Prijs Gevonden</a>
                <% end %><!--@product.min_amount_today.url-->
            <br><br>
            <a href="#home2" class="button button-block button-rounded button-primary button-large">Prijzen Vergelijken</a>
            <h4>Specificaties</h4>
            <ul class="unstyled">
              <% @product.bullets.any? %>
                  <% @product.bullets.each do |bullet| %>
                    <%if bullet.title != "" %>
                  <li><strong><%= bullet.title %>: </strong> <%= bullet.description %></li>
                  <% end %>
              <% end %>

            </ul>
          <!-- adsense -->
          <%= render "adsense" %>
          <!-- adsense end -->
        </div>
        <div class="col-md-3">
          <h3 class="no-margin-top">Omschrijving: <%= @product.title %></h3>
          <%= @product.short_description.html_safe %>...
            <% if @product.amounts_today.any? %>
          <%= link_to "Meer",amount_link_path(@product.min_amount_today.id, @product.min_amount_today.links.last), rel: "nofollow"%>
          <% end %>
        </div>
    </div>
</div>


<!-- tabs -->

<!-- Nav tabs -->
<ul class="nav nav-tabs nav-tabs-ar nav-tabs-ar-white">
  <li class="active"><a href="#home2" data-toggle="tab">Vergelijk Winkels</a></li>
  <li><a href="#profile2" data-toggle="tab">Specificaties</a></li>
  <li><a href="#messages2" data-toggle="tab">Reviews</a></li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
<div class="tab-pane active" id="home2">
  <!-- pricing table -->
                    <div class="bs-example">
                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th>Winkel</th>
                            <th>Naam</th>
                            <th>Prijs</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% if @product.amounts_today.any? %>
                          <% @product.amounts_today.order(:price).each do |amount| %>
                          <tr>
                            <td><%= amount.shop %></a></td><!--<a href="amount.url">-->
                              <td><%=link_to amount.product.title, amount_link_path(amount.id, amount.links.last), rel: "nofollow"  %></td>
                            <td><%=link_to "€#{amount.price.round}", amount_link_path(amount.id, amount.links.last), rel: "nofollow", class: "button button-glow button-rounded button-highlight"  %></td>
                          </tr>
                          <% end %>
                          <% elsif @product.amounts.empty? %>
                          <h6>Geen Prijzen Gevonden.</h6>
                          <% else %>
                          <h6>Geen Prijzen Gevonden.</h6>
                          <% end %>
                        </tbody>
                      </table>
                    </div><!-- /example -->


  <!-- end pricing tabl -->
</div>
<div class="tab-pane" id="profile2">
  <h1><%= @product.title %> Kopen?</h1>
  <%if @product.category.name.downcase == "tv" %>
     <%= render "products/specs/tv_spec" %>
  <% end %>
  <%if @product.category.name.downcase == "koelkasten" %>
   <%= render  "products/specs/koelkast_spec" %>
  <% end %>
  <%if @product.category.name.downcase == "wasmachines" %>
   <%= render "products/specs/wasmachine_spec" %>
  <% end %>
  <%if @product.category.name.downcase == "boormachines" %>
   <%= render "products/specs/boormachine_spec" %>
  <% end %>
  <%if @product.category.name.downcase == "espressomachine" %>
   <%= render "products/specs/espresso_spec" %>
  <% end %>
  <%if @product.category.name.downcase == "autospeakers" %>
   <%= render "products/specs/autoradio_spec" %>
  <% end %>
  <p>
  <%= @product.description.html_safe%>
      <h4><%="De beste #{@product.title} Aanbieding" %></h4>
  <%= render "stuff" %>
  </p>
</div>
<div class="tab-pane" id="messages2">

  <!-- <p>comments</p> -->
</div>
</div>
<% content_for :analytics do %>
 <%= render "layouts/analytics" %>
<% end %>






<!-- <div class="form-group col-md-2">
  <label for="inputPassword2" class="sr-only">Prijs</label>
  <input type="text" class="form-control" placeholder="Prijs">
</div>
 <div class="form-group col-md-8">
   <label for="inputPassword2" class="sr-only">Email adres</label>
   <input type="text" class="form-control"  placeholder="Email Adres">
 </div>
<div class="form-group col-md-2">
 <label for="inputPassword2" class="sr-only">Email adres</label>
   <input type="text" class="form-control"  placeholder="Email Adres">
</div> -->