config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/works_config', as: 'rails_admin'
  devise_for :works
  # mount RailsAdmin::Engine => '/works_config', as: 'rails_admin'
  # devise_for :works

  resources :amounts, only: [:show]do
    resources :links, only: [:show, :index]
  end
get 'links/:id/go' => 'links#go'
get 'contact', to: 'contact#send_mail'
post 'contact', to: 'contact#send_mail'


  resources :referers, only: [:index]
  root 'products#index'
  get 'category/new', to: 'categories#new'
  post 'category/new', to: 'categories#create'
  get 'category/edit/:id', to: 'categories#edit'
  put 'category/edit/:id', to: 'categories#update'
  patch 'category/edit/:id', to: 'categories#update'
  get 'brand/new', to: 'brands#new'
  post 'brand/new', to: 'brands#create'
  get 'brand/edit/:id', to: 'brands#edit'
  put 'brand/edit/:id', to: 'brands#update'
  patch 'brand/edit/:id', to: 'brands#update'
  get 'product/new', to: 'products#new'
  post 'product/new', to: 'products#create'


 resources :products, only: [:edit, :update]

  #resources :products, only: [:new, :create, :edit, :update]
  resources :categories, path: '',only: [:show] do
    resources :brands, path: '', only: [:show] do
      resources :products, path: '',only: [:show] do
        resources :customers, only: [:create]

      end
    end
  end


resources :referers, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_analytics.html.erb
<% if Rails.env == "production"  %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="nl">
  <head>
      <title><%= if content_for?(:title) then yield(:title) + ' | ' end %>Vergelijk Tips</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="google-site-verification" content="l6itWie2625AQRiO95iPCjeyPcaXZIzZwQeuLZEsaAU" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta name='description'
      content='<%= yield_meta_tag(:description, 'Vergelijk de prijzen van uw favoriete product') %>' />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag    'vendors', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag    'shCore', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag    'style-blue', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag    'width-full', media: 'all', 'data-turbolinks-track': 'reload'%>


  </head>
<body>

<div class="sb-site-container">
<div class="boxed">

<header id="header-full-top" class="hidden-xs header-full">
    <div class="container">
        <div class="header-full-title">
            <h1 class="animated fadeInRight"><a href="/">Vergelijk <span>Tips</span></a></h1>
            <p class="animated fadeInRight">Vergelijk Prijzen</p>
        </div>
        <nav class="top-nav">

        </nav>
    </div> <!-- container -->
</header> <!-- header-full -->
<nav class="navbar navbar-default navbar-header-full navbar-dark yamm navbar-static-top" role="navigation" id="header">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a id="ar-brand" class="navbar-brand hidden-lg hidden-md hidden-sm" href="/">Vergelijk <span>Prijzen</span></a>
        </div> <!-- navbar-header -->
        <% if work_signed_in? %>
        <%= form_tag(root_path, :method => "get", id: "search-form") do %>
        <div class="col-sm-6">
          <%= text_field_tag :search, params[:search], placeholder: "Zoek Ean nummer", class: "col-sm-6" %>
          <%= submit_tag "Search" %>
        </div>
        <% if @products.present? %>
            <p>Gevonden</p>
          <% else %>
          <p>Dit Ean nummer is niet gevonden.<%= params[:search] %>.</p>
          <% end %>
        <% end %>
          <ul>
            <li><h2><%= link_to "Home", root_path %></h2></li>
            <li><h2><%= link_to "Nieuw Product", product_new_path %></h2></li>
            <li><h2><%= link_to "Nieuwe Categorie", category_new_path %></h2></li>
            <li><h2><%= link_to "Nieuw Merk", brand_new_path %></h2></li>
            <li><h2><%= link_to "Admin panel", rails_admin_path %></h2></li>
            <li><h2><a href="/referers">Referer</a></h2></li>
          </ul>

        <% end %>
        <!-- Collect the nav links, forms, and other content for toggling -->


</nav>
<!-- End nav -->
<%= yield %>

<!-- Begin Footer -->
<aside id="footer-widgets">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h3 class="footer-widget-title">Sitemap</h3>
                <ul class="list-unstyled three_cols">
                    <li><a href="#">faq</a></li>
                    <li><a href="#">Over ons</a></li>
                    <li><a href="#"></a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <p></p>
            </div>
            <div class="col-md-4">
                <div class="footer-widget">
                    <h3 class="footer-widget-title">links</h3>
                    <div class="row">

                    </div>
                </div>
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</aside> <!-- footer-widgets -->
<footer id="footer">
    <p>&copy; 2016 <a href="#">Vergelijk tips</a>, inc. Alle Rechten behouden.</p>

</footer>

</div> <!-- boxed -->
</div> <!-- sb-site -->


<div id="back-top">
    <a href="#header"><i class="fa fa-chevron-up"></i></a>
</div>




<!-- Syntaxhighlighter -->
<%= javascript_include_tag 'vendors', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'shCore', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'shBrushxml', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'shBrushJScript', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'DropdownHover', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'app', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'holder', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'e-commerce_product', 'data-turbolinks-track': 'reload' %>

<!-- <script src="https://s3-sa-east-1.amazonaws.com/klusgereedschap/assets/js/syntaxhighlighter/shCore.js"></script>
<script src="https://s3-sa-east-1.amazonaws.com/klusgereedschap/assets/js/syntaxhighlighter/shBrushXml.js"></script>
<script src="https://s3-sa-east-1.amazonaws.com/klusgereedschap/assets/js/syntaxhighlighter/shBrushJScript.js"></script>

<script src="https://s3-sa-east-1.amazonaws.com/klusgereedschap/assets/js/DropdownHover.js"></script>
<script src="https://s3-sa-east-1.amazonaws.com/klusgereedschap/assets/js/app.js"></script>
<script src="https://s3-sa-east-1.amazonaws.com/klusgereedschap/assets/js/holder.js"></script>
<script src="https://s3-sa-east-1.amazonaws.com/klusgereedschap/assets/js/e-commerce_product.js"></script>
<%= yield :analytics%> -->
</body>

</html>